import { SEAWATER_DENSITY, STANDARD_GRAVITY } from '../../constants.js';
import { synolakisRunup } from '../tsunami/extendedEffects.js';
import type { Joules, Meters, MetersPerSecond, Seconds } from '../../units.js';
import { J, m } from '../../units.js';
import {
  impactAmplitudeAtDistance,
  impactCavityRadius,
  impactSourceAmplitude,
} from '../tsunami/impact.js';
import { shallowWaterWaveSpeed, tsunamiTravelTime } from '../tsunami/propagation.js';

/**
 * Underwater / contact-water nuclear explosion → tsunami source.
 *
 * The Ward & Asphaug (2000) cavity-radius formula is energy-based and
 * works for any energy source that couples mechanically to a water
 * column. For a nuclear or chemical explosion only a fraction of the
 * total yield ends up as bulk water displacement — the rest goes into
 * compression heating, gas-bubble pulsation, and acoustic radiation.
 * Le Méhauté & Wang (1996) and Glasstone & Dolan (1977) §6 quote
 * mechanical-coupling efficiencies in the 5–15 % range for shallow
 * underwater bursts, peaking near a "scaled depth" z/W^(1/3) ≈ 4 m/kt^(1/3).
 *
 * For the popular-science envelope we use a single canonical
 * coupling fraction of 0.08, which reproduces the Glasstone Table 6.50
 * ≈ 180 m source amplitude for a 1 Mt optimum-depth burst within a
 * factor of two. Outside that regime (very shallow contact bursts on
 * water, or extremely deep submarine bursts) the wave is overestimated
 * — we accept the bias rather than introduce a depth-dependent fit
 * that would still need ±50 % scatter bands to honour the published
 * uncertainty.
 *
 * References:
 *   Glasstone, S. & Dolan, P. J. (1977). "The Effects of Nuclear
 *     Weapons" (3rd ed.), §6.40–§6.65 (Underwater bursts), Table 6.50.
 *   Le Méhauté, B. & Wang, S. (1996). "Water Waves Generated by
 *     Underwater Explosion." Advanced Series on Ocean Engineering 10.
 *     World Scientific. ISBN 978-981-02-2083-3.
 *   Ward, S. N. & Asphaug, E. (2000). "Asteroid Impact Tsunami:
 *     A Probabilistic Hazard Assessment." Icarus 145(1), Eq. 3
 *     (re-used here with a coupling correction).
 */

/** Mechanical coupling fraction for shallow underwater bursts. Tuned
 *  so that 1 Mt at optimum depth reproduces Glasstone Table 6.50's
 *  ≈ 180 m source amplitude. */
export const EXPLOSION_WATER_COUPLING = 0.08;

export interface ExplosionTsunamiInput {
  /** Total explosion yield (J). */
  yieldEnergy: Joules;
  /** Water depth at the burst site (m). Must be > 0 for a wave to
   *  form; the caller decides the threshold. */
  waterDepth: Meters;
  /** Mean basin depth used for the shallow-water travel-time
   *  calculation (m). Defaults to the global ocean mean of 4 km. */
  meanOceanDepth?: Meters;
  /** Beach slope (rad) for the Synolakis run-up. Defaults to
   *  `atan(1/100)` when omitted; the caller (typically the store)
   *  should pass a DEM-driven value when the click point is on a
   *  real coastal slope. */
  coastalBeachSlopeRad?: number;
}

export interface ExplosionTsunamiResult {
  /** Equivalent Ward-Asphaug cavity radius after the coupling
   *  correction (m). */
  cavityRadius: Meters;
  /** Initial wave amplitude at the cavity rim (m). */
  sourceAmplitude: Meters;
  /** Far-field amplitude at 100 km from the burst (m). */
  amplitudeAt100km: Meters;
  /** Far-field amplitude at 1 000 km from the burst (m). */
  amplitudeAt1000km: Meters;
  /** Travel time from the burst to the 100 km contour (s). */
  travelTimeTo100km: Seconds;
  /** Travel time from the burst to the 1 000 km contour (s). */
  travelTimeTo1000km: Seconds;
  /** Coupling fraction applied — echoed for the report tooltip. */
  couplingFraction: number;
  /** Echo of the basin depth used for travel-time. */
  meanOceanDepth: Meters;
  /** Open-ocean phase speed `c = √(g·h)` of a long gravity wave on
   *  the basin (Lamb 1932 §170). At the default 4 km mean depth
   *  this is ≈ 198 m/s ≈ 713 km/h. */
  deepWaterCelerity: MetersPerSecond;
  /** Source-radiated wavelength (m). For an explosion-driven cavity
   *  collapse the dominant wavelength is set by the cavity diameter
   *  (≈ 2 × R_C), the same scaling that holds for impact-driven
   *  cavities under the Ward & Asphaug 2000 framework. */
  sourceWavelength: Meters;
  /** Dominant wave period at the source (s). T = λ / c. */
  dominantPeriod: Seconds;
  /** Synolakis (1987) run-up on a 1:100 plane beach with 10 m
   *  offshore depth, using the 100 km amplitude as the incident
   *  wave. Illustrative coastal-inundation estimate. */
  runupAt100km: Meters;
  /** Estimated inland inundation distance at the 100 km contour
   *  (m). Geometric `runup × cot(slope)` envelope on a 1:100
   *  reference beach (FEMA 55 §3.4). */
  inundationDistanceAt100km: Meters;
  /** Beach slope (rad) actually consumed by the Synolakis run-up. */
  beachSlopeRadUsed: number;
  /** True when {@link beachSlopeRadUsed} came from a DEM sample at
   *  the click site (rather than the 1:100 reference fallback). */
  beachSlopeFromDEM: boolean;
}

/**
 * Compute the explosion-driven tsunami source from a yield and water
 * depth. Returns null when the inputs cannot drive a wave (zero or
 * negative yield, zero water depth).
 */
export function explosionTsunami(input: ExplosionTsunamiInput): ExplosionTsunamiResult | null {
  const yieldJ = input.yieldEnergy as number;
  const depth = input.waterDepth as number;
  if (!Number.isFinite(yieldJ) || yieldJ <= 0) return null;
  if (!Number.isFinite(depth) || depth <= 0) return null;

  const meanOceanDepth = input.meanOceanDepth ?? m(4_000);
  const effectiveEnergy = J(yieldJ * EXPLOSION_WATER_COUPLING);
  const cavityRadius = impactCavityRadius({
    kineticEnergy: effectiveEnergy,
    waterDensity: SEAWATER_DENSITY,
    surfaceGravity: STANDARD_GRAVITY,
  });
  const sourceAmplitude = impactSourceAmplitude(cavityRadius);
  const amp100 = impactAmplitudeAtDistance({
    sourceAmplitude,
    cavityRadius,
    distance: m(100_000),
  });
  const amp1000 = impactAmplitudeAtDistance({
    sourceAmplitude,
    cavityRadius,
    distance: m(1_000_000),
  });

  const celerity = shallowWaterWaveSpeed(meanOceanDepth);
  const wavelength = m(2 * (cavityRadius as number));
  const period = (wavelength / Math.max(celerity, 1e-6)) as Seconds;
  // Use the 100 km contour as the runup anchor for explosions —
  // amplitudes drop off faster than for impacts (smaller cavities),
  // so the 100 km headline is more pedagogically useful than a
  // 1 000 km figure that is often sub-cm. Beach slope: caller-
  // supplied DEM value when in the [1:1000, 1:3] envelope, else
  // 1:100 reference.
  const FALLBACK_SLOPE_RAD = Math.atan(1 / 100);
  const SLOPE_LOWER = Math.atan(1 / 1000);
  const SLOPE_UPPER = Math.atan(1 / 3);
  const supplied = input.coastalBeachSlopeRad;
  const slopeFromDEM =
    supplied !== undefined &&
    Number.isFinite(supplied) &&
    supplied >= SLOPE_LOWER &&
    supplied <= SLOPE_UPPER;
  const beachSlopeRad = slopeFromDEM ? supplied : FALLBACK_SLOPE_RAD;
  const runup100 = synolakisRunup(amp100, beachSlopeRad, m(10));
  const inundation100 = m((runup100 as number) / Math.tan(beachSlopeRad));

  return {
    cavityRadius,
    sourceAmplitude,
    amplitudeAt100km: amp100,
    amplitudeAt1000km: amp1000,
    travelTimeTo100km: tsunamiTravelTime(m(100_000), meanOceanDepth),
    travelTimeTo1000km: tsunamiTravelTime(m(1_000_000), meanOceanDepth),
    couplingFraction: EXPLOSION_WATER_COUPLING,
    meanOceanDepth,
    deepWaterCelerity: celerity,
    sourceWavelength: wavelength,
    dominantPeriod: period,
    runupAt100km: runup100,
    inundationDistanceAt100km: inundation100,
    beachSlopeRadUsed: beachSlopeRad,
    beachSlopeFromDEM: slopeFromDEM,
  };
}
