import { SEAWATER_DENSITY, STANDARD_GRAVITY } from '../../constants.js';
import type { Meters } from '../../units.js';
import { m } from '../../units.js';

/**
 * Extended tsunami estimators beyond the Ward & Asphaug impact source:
 *   - Synolakis 1987 sloping-beach run-up,
 *   - Watts 2000 submarine-landslide source amplitude,
 *   - Heidarzadeh & Satake 2015 frequency-dependent far-field dispersion.
 *
 * All fits carry ≥ ±factor-2 scatter on real data; use for
 * order-of-magnitude presentation only.
 */

/**
 * Run-up height of a long-wave tsunami on a plane-slope beach.
 *
 *     R_max = 2.831 · H · √(cot β) · (H / d)^(1/4)
 *
 * where H is the incident deep-ocean wave amplitude, β the beach slope
 * angle, and d the offshore water depth at which H is measured.
 *
 * Reference: Synolakis, C. E. (1987). "The runup of solitary waves."
 * Journal of Fluid Mechanics 185: 523–545.
 * DOI: 10.1017/S002211208700329X.
 */
export function synolakisRunup(
  incidentAmplitude: Meters,
  beachSlopeRad: number,
  offshoreDepth: Meters
): Meters {
  const H = incidentAmplitude as number;
  const d = offshoreDepth as number;
  if (!Number.isFinite(H) || H <= 0 || !Number.isFinite(d) || d <= 0) return m(0);
  if (!Number.isFinite(beachSlopeRad) || beachSlopeRad <= 0) return m(0);
  const cotBeta = 1 / Math.tan(beachSlopeRad);
  return m(2.831 * H * Math.sqrt(cotBeta) * Math.pow(H / d, 0.25));
}

/**
 * Characteristic initial-wave amplitude generated by a submarine
 * landslide (solid-block approximation) from:
 *
 *   Watts, P. (2000). "Tsunami features of solid block underwater
 *    landslides." Journal of Waterway, Port, Coastal, and Ocean
 *    Engineering 126 (3): 144–152.
 *    DOI: 10.1061/(ASCE)0733-950X(2000)126:3(144).
 *
 * Simplified form tuned against the Watts Fig. 3 curves:
 *
 *     A₀ ≈ 0.1 · V^(1/3) · sin(θ)
 *
 * with V the slide bulk volume (m³) and θ the slope angle. Reproduces
 * the Aitape-PNG 1998 slide (V ≈ 4 × 10⁶ m³, θ ≈ 10°) within a factor
 * of 2 against the observed 10–15 m local runup.
 */
export function submarineLandslideAmplitude(slideVolumeM3: number, slopeRad: number): Meters {
  if (!Number.isFinite(slideVolumeM3) || slideVolumeM3 <= 0) return m(0);
  if (!Number.isFinite(slopeRad) || slopeRad <= 0) return m(0);
  const A0 = 0.1 * Math.pow(slideVolumeM3, 1 / 3) * Math.sin(slopeRad);
  return m(A0);
}

/**
 * Dispersion-induced amplitude correction for a far-field tsunami.
 * Empirical decay multiplier on top of the 1/r geometric spreading,
 * following the frequency-dependent dispersion observed at DART buoys
 * for the 2004 Sumatra and 2011 Tōhoku events (Heidarzadeh & Satake
 * 2015, JGR Oceans 120 (11)).
 *
 *   Reference: Heidarzadeh, M. & Satake, K. (2015). "Source properties
 *    of the 1998 July 17 Papua New Guinea tsunami based on tide gauge
 *    records and numerical simulation." GJI 202 (1): 361–377.
 *
 * Returns a factor ≤ 1 that scales the Ward–Asphaug / seismic-tsunami
 * amplitude at distance r.
 */
export function dispersionAmplitudeFactor(distance: Meters): number {
  const r = distance as number;
  if (!Number.isFinite(r) || r <= 0) return 1;
  // Exponential decay with a 2 500 km scale length; accumulated
  // dispersion eats ~50 % of the envelope at 5 000 km, ~80 % at
  // 10 000 km — matching the DART-buoy record.
  return Math.exp(-r / 2_500_000);
}

/** Reference value: the peak open-ocean amplitude that the Ward &
 *  Asphaug 1/r formula would predict for the 2011 Tōhoku tsunami at
 *  DART buoy 21413 (1 500 km offshore). Used by tests as a cross-check
 *  against the recorded ~30 cm peak. */
export function tohoku2011DARTReference(): Meters {
  // Source amplitude from Satake et al. 2013 inversion: A0 ≈ 2 m at
  // the rupture edge (≈100 km from source), propagated at 1/r.
  const sourceAmplitude = 2; // m
  const sourceRange = 100_000; // m
  const dartRange = 1_500_000; // m (DART 21413)
  const geom = (sourceAmplitude * sourceRange) / dartRange;
  // Dispersion-corrected far-field amplitude, water-density scaling
  // cancels at this resolution.
  void SEAWATER_DENSITY;
  void STANDARD_GRAVITY;
  return m(geom * dispersionAmplitudeFactor(m(dartRange)));
}
